# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev-tutorial',
                'doc_host': 'https://paulmaxus.github.io',
                'git_url': 'https://github.com/paulmaxus/nbdev-tutorial',
                'lib_path': 'nbdev_tutorial'},
  'syms': {'nbdev_tutorial\\core': {'nbdev_tutorial\\core.foo': ('core.html#foo', 'nbdev_tutorial\\core.py')}}}